"""update_order_model

Revision ID: 07dffb995258
Revises: 67d27bfc217e
Create Date: 2024-04-18 07:24:15.446739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07dffb995258'
down_revision: Union[str, None] = '67d27bfc217e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('is_cancel', sa.Boolean(), nullable=True))
    op.add_column('order', sa.Column('cancel_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'cancel_date')
    op.drop_column('order', 'is_cancel')
    # ### end Alembic commands ###
