"""sale_model_update

Revision ID: a3b0edf18375
Revises: 07dffb995258
Create Date: 2024-04-18 09:06:53.190763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3b0edf18375'
down_revision: Union[str, None] = '07dffb995258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order', 'cancel_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sale', 'payment_sale_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale', 'for_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('sale', 'sale_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sale', 'sale_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('sale', 'for_pay',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('sale', 'payment_sale_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('order', 'cancel_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
